M48
; DRILL file {KiCad (6.0.2)} date Thu Feb 26 08:30:53 2026
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-26T08:30:53-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0969
%
G90
G05
T1
X5.7276Y-0.95
X5.7276Y-1.25
X5.7276Y-1.55
X5.7276Y-1.85
T2
X2.0724Y-0.95
X2.0724Y-1.25
X2.0724Y-1.55
X2.0724Y-1.85
T0
M30
